### ISSUE TITLE
Rewizja 1

### ISSUE THREAD

**Issue by jchudzinski** [Languzda/Space-Raider#1]
Proszę o poprawienie następujących funkcjonalności:

- w filmie 2021-06-17_12-34-43.mp3 proszę zwrócić uwagę na kolizje, są momenty gdy pociski znikają nie niszcząc obiektu ani nie wykraczając poza mapę (np. w okolicy sekundy 8, statek 3 od lewej strony, na samej górze)
- asteroidy znikają zamiast wylatywać poza granicę ekranu
- uzależnienie kierunku pocisków od kierunku lotu (zgodnie z animacją) - statek lecąc na boki zmienia swój kąt, proszę zastanowić się nad metodą, aby pociski wylatywały ze statku zgodnie z kierunkiem jego nachylenia (może Pan emirycznie dobrać współczynnik, który będzie równa 1 bez ruchu statku, a w trakcie ruchu będzie przyjmował inną wartość)
- boss (kurczak) strzela z miejsca przesuniętego w prawo, nie ze środka (nie jest to wyjaśnione)
- utworzenie pełnego interfejsu dla klasy Character lub Actor, tak aby wyeliminować odrębne metody np. move_b, move_e...
- wycieki pamięci - zadbanie o zwalnianie pamięci, tam gdzie stosuje Pan wskaźniki (np. funkcja std::vector<PlayerProjectile*> Hero::getBullet())

**Comment by Languzda** [comment]
Poprawiłem Funkcjonalności, które Pan wskazał.

- moment, który Pan wskazał nie jest błędem, tylko wynika z tego że przeciwnicy mają określoną ilość punktów życia oraz pociski określoną ilość obrażeń( na filmiku bazowe pkt życia przeciwnika =3, obrażenia pojedynczego pocisku=2), w celu umożliwienia tworzenia przeciwników z większą ilością pkt życia na kolejnych poziomach. Dodatkowo jednym z wzmocnień dostępnych w grze jest wzmocnienie obrażeń pocisku.
- Dziękuje za zwrócenie uwagi, ma Pan rację że asteroidy powinny wylatywać za ekran i dopiero wtedy znikać.
- Uważam że uzależnienie kierunku pocisków od kierunku lotu mogło by nie potrzebnie utrudnić rozgrywkę (kłóciło by się to z moim pomysłem na rozgrywkę). Pociski wylatują z dolnego działa pokładowego statku.
- Poprawiłem miejsce powstawania pocisków bossa
- Poprawiłem interfejs klasy Actor, dzięki czemu wyeliminowałem nie potrzebne odrębne metody, oraz uprościłem metody w kodzie
- Poprawiłem miejsca zagrożone wyciekiem pamięci, poprzez rezygnacje z tworzenia dodatkowych wskaźników, a wykorzystanie referencji.
